export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export type TYPE_SET_LOGGED_IN_USER = typeof SET_LOGGED_IN_USER;

export const SET_SHOPS = 'SET_SHOPS';
export type TYPE_SET_SHOPS = typeof SET_SHOPS;

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export type TYPE_PUSH_NOTIFICATION = typeof PUSH_NOTIFICATION;

export const PULL_NOTIFICATION = 'PULL_NOTIFICATION';
export type TYPE_PULL_NOTIFICATION = typeof PULL_NOTIFICATION;

export const SET_SUBORDINATE_USER = 'SET_SUBORDINATE_USER';
export type TYPE_SET_SUBORDINATE_USER = typeof SET_SUBORDINATE_USER;

export const REMOVE_LOGGED_IN_USER = 'REMOVE_LOGGED_IN_USER';
export type TYPE_REMOVE_LOGGED_IN_USER = typeof REMOVE_LOGGED_IN_USER;

export const SET_ACTIVE_SHOP = 'SET_ACTIVE_SHOP';
export type TYPE_SET_ACTIVE_SHOP = typeof SET_ACTIVE_SHOP;

export const SET_OVERVIEW_CAMPAIGN = 'SET_OVERVIEW_CAMPAIGN';
export type TYPE_SET_OVERVIEW_CAMPAIGN = typeof SET_OVERVIEW_CAMPAIGN;
